export const ALL_HIRE_REQUEST = "ALL_HIRE_REQUEST";
export const ALL_HIRE_SUCCESS = "ALL_HIRE_SUCCESS";
export const ALL_HIRE_FAIL = "ALL_HIRE_FAIL";

export const ADMIN_HIRE_REQUEST = "ADMIN_HIRE_REQUEST";
export const ADMIN_HIRE_SUCCESS = "ADMIN_HIRE_SUCCESS";
export const ADMIN_HIRE_FAIL = "ADMIN_HIRE_FAIL";

export const NEW_HIRE_REQUEST = "NEW_HIRE_REQUEST";
export const NEW_HIRE_SUCCESS = "NEW_HIRE_SUCCESS";
export const NEW_HIRE_RESET = "NEW_HIRE_RESET";
export const NEW_HIRE_FAIL = "NEW_HIRE_FAIL";

export const UPDATE_HIRE_REQUEST = "UPDATE_HIRE_REQUEST";
export const UPDATE_HIRE_SUCCESS = "UPDATE_HIRE_SUCCESS";
export const UPDATE_HIRE_RESET = "UPDATE_HIRE_RESET";
export const UPDATE_HIRE_FAIL = "UPDATE_HIRE_FAIL";

export const DELETE_HIRE_REQUEST = "DELETE_HIRE_REQUEST";
export const DELETE_HIRE_SUCCESS = "DELETE_HIRE_SUCCESS";
export const DELETE_HIRE_RESET = "DELETE_HIRE_RESET";
export const DELETE_HIRE_FAIL = "DELETE_HIRE_FAIL";

export const HIRE_DETAILS_REQUEST = "HIRE_DETAILS_REQUEST";
export const HIRE_DETAILS_SUCCESS = "HIRE_DETAILS_SUCCESS";
export const HIRE_DETAILS_FAIL = "HIRE_DETAILS_FAIL";

export const NEW_REVIEW_REQUEST = "NEW_REVIEW_REQUEST";
export const NEW_REVIEW_SUCCESS = "NEW_REVIEW_SUCCESS";
export const NEW_REVIEW_RESET = "NEW_REVIEW_RESET";
export const NEW_REVIEW_FAIL = "NEW_REVIEW_FAIL";

export const ALL_REVIEW_REQUEST = "ALL_REVIEW_REQUEST";
export const ALL_REVIEW_SUCCESS = "ALL_REVIEW_SUCCESS";
export const ALL_REVIEW_FAIL = "ALL_REVIEW_FAIL";

export const DELETE_REVIEW_REQUEST = "DELETE_REVIEW_REQUEST";
export const DELETE_REVIEW_SUCCESS = "DELETE_REVIEW_SUCCESS";
export const DELETE_REVIEW_RESET = "DELETE_REVIEW_RESET";
export const DELETE_REVIEW_FAIL = "DELETE_REVIEW_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
