export const ALL_TENDERTABLE_REQUEST = "ALL_TENDERTABLE_REQUEST";
export const ALL_TENDERTABLE_SUCCESS = "ALL_TENDERTABLE_SUCCESS";
export const ALL_TENDERTABLE_FAIL = "ALL_TENDERTABLE_FAIL";

export const ADMIN_TENDERTABLE_REQUEST = "ADMIN_TENDERTABLE_REQUEST";
export const ADMIN_TENDERTABLE_SUCCESS = "ADMIN_TENDERTABLE_SUCCESS";
export const ADMIN_TENDERTABLE_FAIL = "ADMIN_TENDERTABLE_FAIL";

export const NEW_TENDERTABLE_REQUEST = "NEW_TENDERTABLE_REQUEST";
export const NEW_TENDERTABLE_SUCCESS = "NEW_TENDERTABLE_SUCCESS";
export const NEW_TENDERTABLE_RESET = "NEW_TENDERTABLE_RESET";
export const NEW_TENDERTABLE_FAIL = "NEW_TENDERTABLE_FAIL";

export const UPDATE_TENDERTABLE_REQUEST = "UPDATE_TENDERTABLE_REQUEST";
export const UPDATE_TENDERTABLE_SUCCESS = "UPDATE_TENDERTABLE_SUCCESS";
export const UPDATE_TENDERTABLE_RESET = "UPDATE_TENDERTABLE_RESET";
export const UPDATE_TENDERTABLE_FAIL = "UPDATE_TENDERTABLE_FAIL";

export const DELETE_TENDERTABLE_REQUEST = "DELETE_TENDERTABLE_REQUEST";
export const DELETE_TENDERTABLE_SUCCESS = "DELETE_TENDERTABLE_SUCCESS";
export const DELETE_TENDERTABLE_RESET = "DELETE_TENDERTABLE_RESET";
export const DELETE_TENDERTABLE_FAIL = "DELETE_TENDERTABLE_FAIL";

export const TENDERTABLE_DETAILS_REQUEST = "TENDERTABLE_DETAILS_REQUEST";
export const TENDERTABLE_DETAILS_SUCCESS = "TENDERTABLE_DETAILS_SUCCESS";
export const TENDERTABLE_DETAILS_FAIL = "TENDERTABLE_DETAILS_FAIL";

export const NEW_REVIEW_REQUEST = "NEW_REVIEW_REQUEST";
export const NEW_REVIEW_SUCCESS = "NEW_REVIEW_SUCCESS";
export const NEW_REVIEW_RESET = "NEW_REVIEW_RESET";
export const NEW_REVIEW_FAIL = "NEW_REVIEW_FAIL";

export const ALL_REVIEW_REQUEST = "ALL_REVIEW_REQUEST";
export const ALL_REVIEW_SUCCESS = "ALL_REVIEW_SUCCESS";
export const ALL_REVIEW_FAIL = "ALL_REVIEW_FAIL";

export const DELETE_REVIEW_REQUEST = "DELETE_REVIEW_REQUEST";
export const DELETE_REVIEW_SUCCESS = "DELETE_REVIEW_SUCCESS";
export const DELETE_REVIEW_RESET = "DELETE_REVIEW_RESET";
export const DELETE_REVIEW_FAIL = "DELETE_REVIEW_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
