export const ALL_TENDER_REQUEST = "ALL_TENDER_REQUEST";
export const ALL_TENDER_SUCCESS = "ALL_TENDER_SUCCESS";
export const ALL_TENDER_FAIL = "ALL_TENDER_FAIL";

export const ADMIN_TENDER_REQUEST = "ADMIN_TENDER_REQUEST";
export const ADMIN_TENDER_SUCCESS = "ADMIN_TENDER_SUCCESS";
export const ADMIN_TENDER_FAIL = "ADMIN_TENDER_FAIL";

export const NEW_TENDER_REQUEST = "NEW_TENDER_REQUEST";
export const NEW_TENDER_SUCCESS = "NEW_TENDER_SUCCESS";
export const NEW_TENDER_RESET = "NEW_TENDER_RESET";
export const NEW_TENDER_FAIL = "NEW_TENDER_FAIL";

export const UPDATE_TENDER_REQUEST = "UPDATE_TENDER_REQUEST";
export const UPDATE_TENDER_SUCCESS = "UPDATE_TENDER_SUCCESS";
export const UPDATE_TENDER_RESET = "UPDATE_TENDER_RESET";
export const UPDATE_TENDER_FAIL = "UPDATE_TENDER_FAIL";

export const DELETE_TENDER_REQUEST = "DELETE_TENDER_REQUEST";
export const DELETE_TENDER_SUCCESS = "DELETE_TENDER_SUCCESS";
export const DELETE_TENDER_RESET = "DELETE_TENDER_RESET";
export const DELETE_TENDER_FAIL = "DELETE_TENDER_FAIL";

export const TENDER_DETAILS_REQUEST = "TENDER_DETAILS_REQUEST";
export const TENDER_DETAILS_SUCCESS = "TENDER_DETAILS_SUCCESS";
export const TENDER_DETAILS_FAIL = "TENDER_DETAILS_FAIL";

export const NEW_REVIEW_REQUEST = "NEW_REVIEW_REQUEST";
export const NEW_REVIEW_SUCCESS = "NEW_REVIEW_SUCCESS";
export const NEW_REVIEW_RESET = "NEW_REVIEW_RESET";
export const NEW_REVIEW_FAIL = "NEW_REVIEW_FAIL";

export const ALL_REVIEW_REQUEST = "ALL_REVIEW_REQUEST";
export const ALL_REVIEW_SUCCESS = "ALL_REVIEW_SUCCESS";
export const ALL_REVIEW_FAIL = "ALL_REVIEW_FAIL";

export const DELETE_REVIEW_REQUEST = "DELETE_REVIEW_REQUEST";
export const DELETE_REVIEW_SUCCESS = "DELETE_REVIEW_SUCCESS";
export const DELETE_REVIEW_RESET = "DELETE_REVIEW_RESET";
export const DELETE_REVIEW_FAIL = "DELETE_REVIEW_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
